# Copyright 2020 BigBitBus
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# These environment variables are sensitive. They will be converted into a Kubernetes secret.
# Read https://kubernetes.io/docs/concepts/configuration/secret/ to learn more.
# In a prodction setting you would protect this file by not checking it into git or using
# a tool such as sops to securely encrypt this yaml file  before storing it in git
# https://github.com/mozilla/sops 
appsecrets:
    name: api-env-secret
env_in_secret:
  POSTGRES_DB: "todo-postgres-db"
  POSTGRES_USER: "dbuser"
  POSTGRES_PASSWORD: "B1gB1tBu5"

