apiVersion: v1
kind: Pod
metadata:
  name: react-fe
  labels:
    app: react-fe
spec:
  containers:
  - name: react-fe
    image: localhost:32000/react-fe:latest
    ports:
    - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: react-fe-service
spec:
  type: NodePort
  selector:
    app: react-fe
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30008
