apiVersion: v1
kind: Pod
metadata:
  name: go-be
  labels:
    app: go-be
spec:
  containers:
  - name: go-be
    image: localhost:32000/golang-docker:latest
    ports:
    - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: go-be-service
spec:
  type: NodePort
  selector:
    app: go-be
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30007
